server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/udacity?createDatabaseIfNotExist=true
        username: root
        password: root
        initialization-mode: always

    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true

